name: GitHub CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Step
      run: echo "Build Successful"

    - name: Test Step
      run: echo "Testing Successful"

    - name: Deploy Step
      run: echo "Deployment Successful"
